name: ${project.name}
description: ${project.description}
author: Hadde
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}
website: ${project.url}
api-version: 1.13
depend:
  - EldoUtilities

commands:
  hotsprings:
    description: main command of hot springs
    usage: trust the tab completion
    aliases:
      - springs